#' getDSS
#'
#' This function gets returns a single time series from a DSS file generated by the IWFM zone budget utility
#' @param dssFile a DSS file that you've opened with DSSRip
#' @param zone IWFM zone budget zone number
#' @param component the name of the flow component to import; part F of the DSS file
#' @keywords dss iwfm
#' @export
#' @examples
#' getDSS()

getDSS <- function(dssFile, zone, component){
  # create the HEC DSS path string with wildcards
  pth <- paste0("/*/ZONE:",zone,"/*/*/*/",component,"/")
  
  # get all paths that match the pth search string
  pths <- dssrip::getPaths(dssFile, pth)
  
  # return data frame of the time series 
  x <- dssrip::getFullTSC(dssFile, pths) %>%
    broom::tidy(x) %>%
    dplyr::mutate(index=index-1)  # needed to generate the correct dates (end of day)
}