#' getDSS
#'
#'This function gets returns a single time series from a DSS file generated by the IWFM zone budget utility
#' @param dssFile a DSS file that you've opened with DSSRip
#' @param zone IWFM zone budget zone number
#' @param component the name of the flow component to import; part F of the DSS file
#' @keywords dss iwfm
#' @export
#' @examples
#' getDSS()

getDSS <- function(dssFile, zone, component){
  pth <- paste0("/*/ZONE:",zone,"/*/*/*/",component,"/")
  pths <- dssrip::getPaths(dssFile, pth)
  x <- dssrip::getFullTSC(dssFile, pths) %>%
    broom::tidy(x) %>%
    dplyr::mutate(index=index-1)
}